/**
 * Mixin 静态校验与生成产物一致性检查.
 *
 * 校验:
 * 1. Manifest 中的 mixin 文件、Catalog 符号、mixin 类名与源码一致
 * 2. 重命名后的旧 Catalog 符号不得继续被引用
 * 3. BlueprintCatalog.ts 与 mixin-imports.ts 和 Manifest 同步
 * 4. 使用 getMixinRuntimeState 的 Mixin 必须配对 clearMixinRuntimeState
 * 5. Manifest executionContext 与 mixin-imports.{shared,client,server}.ts 一致
 * 6. Mixins 禁止 GetActorOfClass / Api.setTransport (DevHttp Feature 除外)
 *
 * 蓝图硬编码路径与 console.* 规则由 ESLint 负责 (npm run lint).
 *
 * 用法: node check-mixins.mjs [--project=<项目根>] [--manifest=...] [--catalog=...] [--index=...]
 */

import fs from 'node:fs';
import path from 'node:path';
import {
  EXECUTION_CONTEXTS,
  loadManifest,
  makeCatalogSource,
  normalizeExecutionContext,
  normalizeProjectRelativePath,
  toProjectPath,
  walkTypeScriptFiles,
} from '../Plugins/PuertsMixinAutomation/Scripts/blueprint-manifest-utils.mjs';

const args = process.argv.slice(2);

/** 从命令行读取 --name=value 参数 */
function readArg(name, fallback) {
  const prefix = `--${name}=`;
  const value = args.find((arg) => arg.startsWith(prefix));
  return value ? value.slice(prefix.length) : fallback;
}

/** 统一换行符, 避免 Windows/Unix 差异导致生成产物比对失败 */
function normalizeNewlines(source) {
  return source.replace(/\r\n/g, '\n');
}

/** 将 mixin 源文件路径转为 mixin-imports.ts 中可用的相对 import 路径 */
function toImportPath(indexDir, file) {
  let importPath = path.relative(indexDir, file).replace(/\\/g, '/').replace(/\.ts$/, '');
  if (!importPath.startsWith('.')) {
    importPath = `./${importPath}`;
  }
  return importPath;
}

/**
 * 根据 Manifest 推导指定 executionContext 的 mixin-imports 期望内容.
 */
function makeIndexSourceForContext(projectRoot, manifest, indexFile, context) {
  const indexDir = path.dirname(indexFile);
  const imports = manifest.blueprints
    .filter((entry) => !entry.missing && entry.autoManaged !== false)
    .filter((entry) => normalizeExecutionContext(entry.executionContext) === context)
    .map((entry) => toProjectPath(projectRoot, normalizeProjectRelativePath(entry.mixinFile)))
    .filter((file) => fs.existsSync(file))
    .sort((a, b) => a.localeCompare(b))
    .map((file) => `import "${toImportPath(indexDir, file)}";`);

  return [
    '// Auto-generated by PuertsMixinAutomation. Do not edit.',
    ...imports,
    '',
  ].join('\n');
}

/**
 * 根据 Manifest 推导 mixin-imports.ts 的期望内容 (全量, 兼容旧工具链).
 */
function makeIndexSource(projectRoot, manifest, indexFile) {
  const indexDir = path.dirname(indexFile);
  const imports = manifest.blueprints
    .filter((entry) => !entry.missing && entry.autoManaged !== false)
    .map((entry) => toProjectPath(projectRoot, normalizeProjectRelativePath(entry.mixinFile)))
    .filter((file) => fs.existsSync(file))
    .sort((a, b) => a.localeCompare(b))
    .map((file) => `import "${toImportPath(indexDir, file)}";`);

  return [
    '// Auto-generated by PuertsMixinAutomation. Do not edit.',
    ...imports,
    '',
  ].join('\n');
}

/** 跳过自动生成目录及 BlueprintCatalog, 只扫描手写 TypeScript */
function isGeneratedFile(file, catalogFile) {
  const normalized = path.resolve(file).replace(/\\/g, '/');
  return normalized === path.resolve(catalogFile).replace(/\\/g, '/')
    || normalized.includes('/TypeScript/Mixins/_generated/');
}

/**
 * 校验 Manifest 条目与 mixin 源文件一致:
 * 文件存在、catalogSymbol / mixinClassName 出现、且 registerBlueprintMixin 调用匹配.
 */
function checkManifestEntries(projectRoot, manifest) {
  const errors = [];
  for (const entry of manifest.blueprints.filter((item) => !item.missing)) {
    const mixinFile = toProjectPath(projectRoot, normalizeProjectRelativePath(entry.mixinFile));
    const relativeFile = path.relative(projectRoot, mixinFile).replace(/\\/g, '/');
    if (!fs.existsSync(mixinFile)) {
      errors.push(`${entry.mixinFile}: mixin file listed in manifest does not exist.`);
      continue;
    }

    const source = fs.readFileSync(mixinFile, 'utf8');
    if (!new RegExp(`\\b${entry.catalogSymbol}\\b`).test(source)) {
      errors.push(`${relativeFile}: missing catalog symbol ${entry.catalogSymbol}.`);
    }
    if (!new RegExp(`\\b${entry.mixinClassName}\\b`).test(source)) {
      errors.push(`${relativeFile}: missing mixin class ${entry.mixinClassName}.`);
    }
    if (!new RegExp(`registerBlueprintMixin\\(\\s*${entry.catalogSymbol}\\s*,\\s*${entry.mixinClassName}\\s*\\)`).test(source)) {
      errors.push(`${relativeFile}: missing registerBlueprintMixin(${entry.catalogSymbol}, ${entry.mixinClassName}).`);
    }
  }
  return errors;
}

/**
 * 蓝图重命名后, Manifest 会记录 previousCatalogSymbols.
 * 扫描手写代码, 确保旧符号已全部替换为新符号.
 */
function checkPreviousSymbols(projectRoot, manifest, catalogFile) {
  const errors = [];
  const previousSymbols = manifest.blueprints.flatMap((entry) => entry.previousCatalogSymbols ?? []);
  if (previousSymbols.length === 0) {
    return errors;
  }

  for (const file of walkTypeScriptFiles(path.resolve(projectRoot, 'TypeScript'))) {
    if (isGeneratedFile(file, catalogFile)) {
      continue;
    }
    const source = fs.readFileSync(file, 'utf8');
    const relativeFile = path.relative(projectRoot, file).replace(/\\/g, '/');
    for (const symbol of previousSymbols) {
      if (new RegExp(`\\b${symbol}\\b`).test(source)) {
        errors.push(`${relativeFile}: references renamed catalog symbol ${symbol}.`);
      }
    }
  }
  return errors;
}

/**
 * 使用 getMixinRuntimeState 的 Mixin 必须在 EndPlay/Destruct 中调用 clearMixinRuntimeState.
 */
function checkMixinStatePairing(projectRoot, catalogFile) {
  const errors = [];
  const mixinRoot = path.resolve(projectRoot, 'TypeScript/Mixins/Blueprints');

  for (const file of walkTypeScriptFiles(mixinRoot)) {
    if (isGeneratedFile(file, catalogFile)) {
      continue;
    }

    const source = fs.readFileSync(file, 'utf8');
    const usesGet = /getMixinRuntimeState\s*\(/.test(source);
    const usesClear = /clearMixinRuntimeState\s*\(/.test(source);
    if (usesGet && !usesClear) {
      const relativeFile = path.relative(projectRoot, file).replace(/\\/g, '/');
      errors.push(
        `${relativeFile}: uses getMixinRuntimeState but missing clearMixinRuntimeState in EndPlay/Destruct.`
      );
    }
  }

  return errors;
}

/** Manifest 条目必须包含合法 executionContext. */
function checkManifestExecutionContext(manifest) {
  const errors = [];
  for (const entry of manifest.blueprints.filter((item) => !item.missing && item.autoManaged !== false)) {
    if (!entry.executionContext) {
      errors.push(`${entry.mixinFile}: missing executionContext (Shared | Client | Server).`);
      continue;
    }

    try {
      normalizeExecutionContext(entry.executionContext);
    } catch {
      errors.push(`${entry.mixinFile}: invalid executionContext "${entry.executionContext}".`);
    }
  }

  return errors;
}

/**
 * Mixins 层禁止跨 Actor 扫场景与 Transport 注入 (DevHttp Feature 在 Game 层负责).
 */
function checkMixinAntiPatterns(projectRoot, catalogFile) {
  const errors = [];
  const mixinRoot = path.resolve(projectRoot, 'TypeScript/Mixins');
  const forbiddenPatterns = [
    { pattern: /GameplayStatics\.GetActorOfClass\s*\(/, message: 'GameplayStatics.GetActorOfClass is forbidden in Mixins.' },
    { pattern: /GameplayStatics\.GetAllActorsOfClass\s*\(/, message: 'GameplayStatics.GetAllActorsOfClass is forbidden in Mixins.' },
    { pattern: /\bApi\.setTransport\s*\(/, message: 'Api.setTransport is forbidden in Mixins; use DevHttpModule.' },
    { pattern: /\bsetupTestMockTransport\s*\(/, message: 'setupTestMockTransport is forbidden in Mixins; use DevHttpModule.' },
  ];

  for (const file of walkTypeScriptFiles(mixinRoot)) {
    if (isGeneratedFile(file, catalogFile)) {
      continue;
    }

    const source = fs.readFileSync(file, 'utf8');
    const relativeFile = path.relative(projectRoot, file).replace(/\\/g, '/');
    for (const { pattern, message } of forbiddenPatterns) {
      if (pattern.test(source)) {
        errors.push(`${relativeFile}: ${message}`);
      }
    }
  }

  return errors;
}

// --- 路径配置 (均可通过 CLI 覆盖) ---

const projectRoot = path.resolve(readArg('project', process.cwd()));
const indexFile = path.resolve(projectRoot, readArg('index', 'TypeScript/Mixins/_generated/mixin-imports.ts'));
const manifestFile = path.resolve(projectRoot, readArg('manifest', 'TypeScript/Mixins/_generated/blueprint-manifest.json'));
const catalogFile = path.resolve(projectRoot, readArg('catalog', 'TypeScript/Blueprints/_generated/BlueprintCatalog.ts'));

// --- 执行校验 ---

const errors = [];
const manifest = loadManifest(manifestFile);

errors.push(...checkManifestEntries(projectRoot, manifest));
errors.push(...checkManifestExecutionContext(manifest));
errors.push(...checkPreviousSymbols(projectRoot, manifest, catalogFile));
errors.push(...checkMixinStatePairing(projectRoot, catalogFile));
errors.push(...checkMixinAntiPatterns(projectRoot, catalogFile));

// 生成产物与 Manifest 推导结果逐字比对, 不一致则提示重新生成
const expectedCatalogSource = makeCatalogSource(manifest);
const actualCatalogSource = fs.existsSync(catalogFile) ? fs.readFileSync(catalogFile, 'utf8') : '';
if (normalizeNewlines(actualCatalogSource) !== expectedCatalogSource) {
  errors.push(`${path.relative(projectRoot, catalogFile)} is out of date. Run npm run gen:blueprint-catalog.`);
}

const expectedIndexSource = makeIndexSource(projectRoot, manifest, indexFile);
const actualIndexSource = fs.existsSync(indexFile) ? fs.readFileSync(indexFile, 'utf8') : '';
if (normalizeNewlines(actualIndexSource) !== expectedIndexSource) {
  errors.push(`${path.relative(projectRoot, indexFile)} is out of date. Run npm run gen:mixin-index.`);
}

const indexDir = path.dirname(indexFile);
for (const context of EXECUTION_CONTEXTS) {
  const contextFile = path.join(indexDir, `mixin-imports.${context.toLowerCase()}.ts`);
  const expectedContextSource = makeIndexSourceForContext(projectRoot, manifest, indexFile, context);
  const actualContextSource = fs.existsSync(contextFile) ? fs.readFileSync(contextFile, 'utf8') : '';
  if (normalizeNewlines(actualContextSource) !== expectedContextSource) {
    errors.push(`${path.relative(projectRoot, contextFile)} is out of date. Run npm run gen:mixin-index.`);
  }
}

if (errors.length > 0) {
  console.error('[check-mixins] failed:');
  for (const error of errors) {
    console.error(`- ${error}`);
  }
  process.exit(1);
}

console.log(`[check-mixins] ok (${manifest.blueprints.filter((entry) => !entry.missing).length} manifest blueprint(s))`);
