/**
 * Mixin 静态校验与生成产物一致性检查.
 *
 * 校验:
 * 1. 手写 TypeScript 禁止直接硬编码 UE.Class.Load('/Game/...') 和 UE.Game.Blueprints 类型路径
 * 2. Manifest 中的 mixin 文件、Catalog 符号、mixin 类名与源码一致
 * 3. BlueprintCatalog.ts 与 mixin-imports.ts 和 Manifest 同步
 */

import fs from 'node:fs';
import path from 'node:path';
import {
  loadManifest,
  makeCatalogSource,
  normalizeProjectRelativePath,
  toProjectPath,
  walkTypeScriptFiles,
} from '../Plugins/PuertsMixinAutomation/Scripts/blueprint-manifest-utils.mjs';

const args = process.argv.slice(2);

function readArg(name, fallback) {
  const prefix = `--${name}=`;
  const value = args.find((arg) => arg.startsWith(prefix));
  return value ? value.slice(prefix.length) : fallback;
}

function normalizeNewlines(source) {
  return source.replace(/\r\n/g, '\n');
}

function toImportPath(indexDir, file) {
  let importPath = path.relative(indexDir, file).replace(/\\/g, '/').replace(/\.ts$/, '');
  if (!importPath.startsWith('.')) {
    importPath = `./${importPath}`;
  }
  return importPath;
}

function makeIndexSource(projectRoot, manifest, indexFile) {
  const indexDir = path.dirname(indexFile);
  const imports = manifest.blueprints
    .filter((entry) => !entry.missing && entry.autoManaged !== false)
    .map((entry) => toProjectPath(projectRoot, normalizeProjectRelativePath(entry.mixinFile)))
    .filter((file) => fs.existsSync(file))
    .sort((a, b) => a.localeCompare(b))
    .map((file) => `import "${toImportPath(indexDir, file)}";`);

  return [
    '// Auto-generated by PuertsMixinAutomation. Do not edit.',
    ...imports,
    '',
  ].join('\n');
}

function isGeneratedFile(file, catalogFile) {
  const normalized = path.resolve(file).replace(/\\/g, '/');
  return normalized === path.resolve(catalogFile).replace(/\\/g, '/')
    || normalized.includes('/TypeScript/Mixins/_generated/');
}

function checkNoHardcodedBlueprintReferences(projectRoot, catalogFile) {
  const errors = [];
  const typeScriptRoot = path.resolve(projectRoot, 'TypeScript');
  for (const file of walkTypeScriptFiles(typeScriptRoot)) {
    if (isGeneratedFile(file, catalogFile)) {
      continue;
    }

    const relativeFile = path.relative(projectRoot, file).replace(/\\/g, '/');
    const source = fs.readFileSync(file, 'utf8');
    if (/UE\.Class\.Load\(\s*["']\/Game\//.test(source)) {
      errors.push(`${relativeFile}: do not hardcode UE.Class.Load('/Game/...'); use BlueprintCatalog APIs.`);
    }
    if (/UE\.Game\.Blueprints\./.test(source)) {
      errors.push(`${relativeFile}: do not reference UE.Game.Blueprints directly; use BlueprintInstance<typeof XxxBlueprint>.`);
    }
  }
  return errors;
}

function checkManifestEntries(projectRoot, manifest) {
  const errors = [];
  for (const entry of manifest.blueprints.filter((item) => !item.missing)) {
    const mixinFile = toProjectPath(projectRoot, normalizeProjectRelativePath(entry.mixinFile));
    const relativeFile = path.relative(projectRoot, mixinFile).replace(/\\/g, '/');
    if (!fs.existsSync(mixinFile)) {
      errors.push(`${entry.mixinFile}: mixin file listed in manifest does not exist.`);
      continue;
    }

    const source = fs.readFileSync(mixinFile, 'utf8');
    if (!new RegExp(`\\b${entry.catalogSymbol}\\b`).test(source)) {
      errors.push(`${relativeFile}: missing catalog symbol ${entry.catalogSymbol}.`);
    }
    if (!new RegExp(`\\b${entry.mixinClassName}\\b`).test(source)) {
      errors.push(`${relativeFile}: missing mixin class ${entry.mixinClassName}.`);
    }
    if (!new RegExp(`registerBlueprintMixin\\(\\s*${entry.catalogSymbol}\\s*,\\s*${entry.mixinClassName}\\s*\\)`).test(source)) {
      errors.push(`${relativeFile}: missing registerBlueprintMixin(${entry.catalogSymbol}, ${entry.mixinClassName}).`);
    }
  }
  return errors;
}

function checkPreviousSymbols(projectRoot, manifest, catalogFile) {
  const errors = [];
  const previousSymbols = manifest.blueprints.flatMap((entry) => entry.previousCatalogSymbols ?? []);
  if (previousSymbols.length === 0) {
    return errors;
  }

  for (const file of walkTypeScriptFiles(path.resolve(projectRoot, 'TypeScript'))) {
    if (isGeneratedFile(file, catalogFile)) {
      continue;
    }
    const source = fs.readFileSync(file, 'utf8');
    const relativeFile = path.relative(projectRoot, file).replace(/\\/g, '/');
    for (const symbol of previousSymbols) {
      if (new RegExp(`\\b${symbol}\\b`).test(source)) {
        errors.push(`${relativeFile}: references renamed catalog symbol ${symbol}.`);
      }
    }
  }
  return errors;
}

const projectRoot = path.resolve(readArg('project', process.cwd()));
const indexFile = path.resolve(projectRoot, readArg('index', 'TypeScript/Mixins/_generated/mixin-imports.ts'));
const manifestFile = path.resolve(projectRoot, readArg('manifest', 'TypeScript/Mixins/_generated/blueprint-manifest.json'));
const catalogFile = path.resolve(projectRoot, readArg('catalog', 'TypeScript/Blueprints/_generated/BlueprintCatalog.ts'));

const errors = [];
const manifest = loadManifest(manifestFile);

errors.push(...checkNoHardcodedBlueprintReferences(projectRoot, catalogFile));
errors.push(...checkManifestEntries(projectRoot, manifest));
errors.push(...checkPreviousSymbols(projectRoot, manifest, catalogFile));

const expectedCatalogSource = makeCatalogSource(manifest);
const actualCatalogSource = fs.existsSync(catalogFile) ? fs.readFileSync(catalogFile, 'utf8') : '';
if (normalizeNewlines(actualCatalogSource) !== expectedCatalogSource) {
  errors.push(`${path.relative(projectRoot, catalogFile)} is out of date. Run npm run gen:blueprint-catalog.`);
}

const expectedIndexSource = makeIndexSource(projectRoot, manifest, indexFile);
const actualIndexSource = fs.existsSync(indexFile) ? fs.readFileSync(indexFile, 'utf8') : '';
if (normalizeNewlines(actualIndexSource) !== expectedIndexSource) {
  errors.push(`${path.relative(projectRoot, indexFile)} is out of date. Run npm run gen:mixin-index.`);
}

if (errors.length > 0) {
  console.error('[check-mixins] failed:');
  for (const error of errors) {
    console.error(`- ${error}`);
  }
  process.exit(1);
}

console.log(`[check-mixins] ok (${manifest.blueprints.filter((entry) => !entry.missing).length} manifest blueprint(s))`);
